version: '3.8'
services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: BookApp
    container_name: mysqlcontainer
    image: mysql:8.1
    volumes:
      - myvolume:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - mynetwork2
  pmadmin:
    environment:
      PMA_HOST: mysqlcontainer
      PMA_PORT: 3306
    container_name: phpmyadmincontainer
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    networks:
      - mynetwork2

  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - myvolume:/var/lib/mysql
    ports:
      - 3000:3000
      - 3001:3001
    cap_add:
      - IPC_LOCK
    restart: unless-stopped

volumes:
  myvolume:

networks:
  mynetwork2:
