version: '3.8'
services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: BookApp
    container_name: mysqlcontainer
    image: mysql:8.1
    volumes:
      - myvolume:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - mynetwork2
  pmadmin:
    environment:
      PMA_HOST: mysqlcontainer
      PMA_PORT: 3306
    container_name: phpmyadmincontainer
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    networks:
      - mynetwork2

volumes:
  myvolume:

networks:
  mynetwork2:
